---
name: Language-Befunge-Debugger
version: 0.3.6
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: a graphical debugger for Language::Befunge
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Getopt::Euclid: 0
  Language::Befunge: 4.01
  List::MoreUtils: 0
  POE: 0
  Readonly: 0
  Tk: 0
  Tk::TableMatrix: 0
  Tk::ToolBar: 0
  perl: 5.008
build_requires:
  Getopt::Euclid: 0
  Language::Befunge: 4.01
  List::MoreUtils: 0
  POE: 0
  Readonly: 0
  Test::More: 0
  Tk: 0
  Tk::TableMatrix: 0
  Tk::ToolBar: 0
  perl: 5.008
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Language::Befunge::Debugger:
    file: lib/Language/Befunge/Debugger.pm
    version: 0.3.6
  Language::Befunge::Debugger::Breakpoints:
    file: lib/Language/Befunge/Debugger/Breakpoints.pm
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
